//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiStefanini
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Genero { get; set; }
        public System.DateTime Nascimento { get; set; }
        public int Login_Id { get; set; }
        public int Endereco_Id { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual Login Login { get; set; }
    }
}
