//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Endereco
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Endereco()
    {
        this.Usuario = new HashSet<Usuario>();
    }
    public Endereco(string Cep, string logradouro, string bairro, string cidade, string uf)
    {
        this.Cep = Cep;
        this.Logradouro = logradouro;
        this.Bairro = bairro;
        this.Cidade = cidade;
        this.UF = uf;

    }

    public int Id { get; set; }
    public string Cep { get; set; }
    public string Logradouro { get; set; }
    public string Bairro { get; set; }
    public string Cidade { get; set; }
    public string UF { get; set; }
    public string Complemento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Usuario> Usuario { get; set; }
}

public partial class Login
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Login()
    {
        this.Usuario = new HashSet<Usuario>();
    }
    public Login(string login, string senha)
    {
        this.Login1 = login;
        this.Senha = senha;
    }
    public int Id { get; set; }
    public string Login1 { get; set; }
    public string Senha { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Usuario> Usuario { get; set; }
}

public partial class Usuario
{

    public Usuario(string nome, string genero, DateTime nascimento)
    {
        this.Nome = nome;
        this.Genero = genero;
        this.Nascimento = nascimento;
    }

    public int Id { get; set; }
    public string Nome { get; set; }
    public string Genero { get; set; }
    public System.DateTime Nascimento { get; set; }
    public int Login_Id { get; set; }
    public int Endereco_Id { get; set; }

    public virtual Endereco Endereco { get; set; }
    public virtual Login Login { get; set; }
}

public partial class SelectEnderecoFromCep_Result
{
    public int Id { get; set; }
    public string Cep { get; set; }
    public string Logradouro { get; set; }
    public string Bairro { get; set; }
    public string Cidade { get; set; }
    public string UF { get; set; }
    public string Complemento { get; set; }
}

public partial class SelectEnderecoFromCidade_Result
{
    public int Id { get; set; }
    public string Cep { get; set; }
    public string Logradouro { get; set; }
    public string Bairro { get; set; }
    public string Cidade { get; set; }
    public string UF { get; set; }
    public string Complemento { get; set; }
}

public partial class SelectEnderecoFromId_Result
{
    public int Id { get; set; }
    public string Cep { get; set; }
    public string Logradouro { get; set; }
    public string Bairro { get; set; }
    public string Cidade { get; set; }
    public string UF { get; set; }
    public string Complemento { get; set; }
}

public partial class SelectEnderecos_Result
{
    public int Id { get; set; }
    public string Cep { get; set; }
    public string Logradouro { get; set; }
    public string Bairro { get; set; }
    public string Cidade { get; set; }
    public string UF { get; set; }
    public string Complemento { get; set; }
}

public partial class SelectLogin_Result
{
    public int Id { get; set; }
    public string Login { get; set; }
    public string Senha { get; set; }
}

public partial class SelectLoginFromId_Result
{
    public int Id { get; set; }
    public string Login { get; set; }
    public string Senha { get; set; }
}

public partial class SelectLoginFromLogin_Result
{
    public int Id { get; set; }
    public string Login { get; set; }
    public string Senha { get; set; }
}

public partial class SelectUsuarioFromCep_Result
{
    public int Id { get; set; }
    public string Nome { get; set; }
    public string Genero { get; set; }
    public System.DateTime Nascimento { get; set; }
    public int Login_Id { get; set; }
    public int Endereco_Id { get; set; }
}

public partial class SelectUsuarioFromLogin_Result
{
    public int Id { get; set; }
    public string Nome { get; set; }
    public string Genero { get; set; }
    public System.DateTime Nascimento { get; set; }
    public int Login_Id { get; set; }
    public int Endereco_Id { get; set; }
}

public partial class SelectUsuarioFromNome_Result
{
    public int Id { get; set; }
    public string Nome { get; set; }
    public string Genero { get; set; }
    public System.DateTime Nascimento { get; set; }
    public int Login_Id { get; set; }
    public int Endereco_Id { get; set; }
}

public partial class SelectUsuarios_Result
{
    public int Id { get; set; }
    public string Nome { get; set; }
    public string Genero { get; set; }
    public System.DateTime Nascimento { get; set; }
    public int Login_Id { get; set; }
    public int Endereco_Id { get; set; }
}
